### ISSUE TITLE
FleetAutoscaler bug

### ISSUE THREAD

**Issue by RayMeibergen** [googleforgames/agones#2052] opened 2021-04-07 06:16 UTC
**What happened**:

we found a bug by using FleetAutoscaler
when we set FleetAutoscaler such as :

```
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: gameserver-autoscaler
spec:
  fleetName: test-gameserver
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 3
      maxReplicas: 100
```      

we will get like this.
so far so good
```
NAME                            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserver   Packed       3         3         0           0       43d
NAME                                        READY   STATUS    RESTARTS   AGE
gameserver-xkhxz-77mbr   2/2     Running   0          13s
gameserver-xkhxz-t44r9   2/2     Running   0          14s
gameserver-xkhxz-xn4bz   2/2     Running   0          22s
```

now  Allocat  2 gameservers
we will get 2 Ready and 2 Allocated server
```
NAME                            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserver   Packed       4         4         2           2       43d
NAME                                        READY   STATUS    RESTARTS   AGE
gameserver-xkhxz-77mbr   2/2     Running   0          4m41s
gameserver-xkhxz-g47f7   2/2     Running   0          42s
gameserver-xkhxz-t44r9   2/2     Running   0          4m42s
gameserver-xkhxz-xn4bz   2/2     Running   0          4m50s
NAME                                        STATE       ADDRESS          PORT   NODE                                               AGE
gameserver-xkhxz-77mbr   Allocated   18.181.197.173   7190   ip-10-188-11-12.ap-northeast-1.compute.internal    4m42s
gameserver-xkhxz-g47f7   Ready       3.112.57.82      7233   ip-10-188-36-130.ap-northeast-1.compute.internal   43s
gameserver-xkhxz-t44r9   Allocated   3.112.57.82      7842   ip-10-188-36-130.ap-northeast-1.compute.internal   4m43s
gameserver-xkhxz-xn4bz   Ready       18.181.197.173   7518   ip-10-188-11-12.ap-northeast-1.compute.internal    4m51s
```

now when we shutdown one gameserver it will create new server and gonna delete a gameserver which was Ready
check it below.

```
NAME                            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserver   Packed       4         4         1           2       43d
NAME                                        READY   STATUS        RESTARTS   AGE
gameserver-xkhxz-77mbr   2/2     Running       0          4m58s
gameserver-xkhxz-g47f7   2/2     Running       0          59s
gameserver-xkhxz-gm9ll   2/2     Running       0          4s
gameserver-xkhxz-t44r9   2/2     Terminating   0          4m59s
gameserver-xkhxz-xn4bz   2/2     Running       0          5m7s
NAME                                        STATE       ADDRESS          PORT   NODE                                               AGE
gameserver-xkhxz-77mbr   Allocated   18.181.197.173   7190   ip-10-188-11-12.ap-northeast-1.compute.internal    4m59s
gameserver-xkhxz-g47f7   Ready       3.112.57.82      7233   ip-10-188-36-130.ap-northeast-1.compute.internal   60s
gameserver-xkhxz-gm9ll   Scheduled   3.112.57.82      7838   ip-10-188-36-130.ap-northeast-1.compute.internal   5s   <--- new server
gameserver-xkhxz-t44r9   Shutdown    3.112.57.82      7842   ip-10-188-36-130.ap-northeast-1.compute.internal   5m  <--- shutdown server
gameserver-xkhxz-xn4bz   Ready       18.181.197.173   7518   ip-10-188-11-12.ap-northeast-1.compute.internal    5m8s <--- this server disappear
```

delete gameserver-xkhxz-xn4bz , which was ready..
```
NAME                            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserver   Packed       3         3         1           1       43d
NAME                                        READY   STATUS    RESTARTS   AGE
gameserver-xkhxz-77mbr   2/2     Running   0          5m15s
gameserver-xkhxz-g47f7   2/2     Running   0          76s
gameserver-xkhxz-gm9ll   2/2     Running   0          21s
NAME                                        STATE       ADDRESS          PORT   NODE                                               AGE
gameserver-xkhxz-77mbr   Allocated   18.181.197.173   7190   ip-10-188-11-12.ap-northeast-1.compute.internal    5m16s
gameserver-xkhxz-g47f7   Ready       3.112.57.82      7233   ip-10-188-36-130.ap-northeast-1.compute.internal   77s
gameserver-xkhxz-gm9ll   Scheduled   3.112.57.82      7838   ip-10-188-36-130.ap-northeast-1.compute.internal   22s
```

```
NAME                            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserver   Packed       3         3         1           2       43d
NAME                                        READY   STATUS    RESTARTS   AGE
gameserver-xkhxz-77mbr   2/2     Running   0          17m
gameserver-xkhxz-g47f7   2/2     Running   0          13m
gameserver-xkhxz-gm9ll   2/2     Running   0          12m
NAME                                        STATE       ADDRESS          PORT   NODE                                               AGE
gameserver-xkhxz-77mbr   Allocated   18.181.197.173   7190   ip-10-188-11-12.ap-northeast-1.compute.internal    17m
gameserver-xkhxz-g47f7   Ready       3.112.57.82      7233   ip-10-188-36-130.ap-northeast-1.compute.internal   13m
gameserver-xkhxz-gm9ll   Ready       3.112.57.82      7838   ip-10-188-36-130.ap-northeast-1.compute.internal   12m
```

**What you expected to happen**:

when we shutdown Allocated gameserver, it should keep the Ready Server.

**How to reproduce it (as minimally and precisely as possible)**:

check abouve.

**Anything else we need to know?**:

**Environment**:
- Agones version: agones-1.13.0
- Kubernetes version (use `kubectl version`): v1.19.6-eks-49a6c0
- Cloud provider or hardware configuration:
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment] 2021-04-07 07:39
If I'm following your report correctly, the states were:

| Allocated | Ready | Notes |
| --------- | ---- | --- |
| 0 | 3 | 3 ready game servers created based on the min replicas parameter |
| 2 | 2 | 2 ready game servers running based on the buffer size parameter |
| 1 | 2 | 2 ready game servers running based on the buffer size parameter |

And each state looks correct. 

But the issue is that during the transition from state 2 to state 3, there was unnecessary churn in the system, because you would expect the 2 ready game servers in state 2 (`gameserver-xkhxz-g47f7` and `gameserver-xkhxz-xn4bz`) to still be the 2 ready game servers in state 3.

So the question is when the allocated game servers is shutdown, why is a new game server created (`gameserver-xkhxz-gm9ll`), because that creation causes the system to exceed the necessary number of game servers in the buffer, causing an existing ready game server to be removed.

**Comment by RayMeibergen** [comment] 2021-04-07 08:38
thanks for your reply.

I now understand why is this happened.
Let me check the sequence.

step1. I will Allocate gameserver
step2. I will shutdown the gameserver
step3. new gameserver gonna create
step4. delete the old gameserver which is "Ready".

if this is correct, does it mean when I  shutdown the Allocated gameserver, it will stop the "Ready Server" every time?

**Comment by roberthbailey** [comment] 2021-04-20 20:32
I'm going to re-open this since your last comment asked another question.

**Comment by jie-bao** [comment] 2021-04-27 09:54
I met the same issue. I think that's because https://github.com/googleforgames/agones/blob/main/pkg/fleetautoscalers/controller.go#L215.

When a gameserver is shutdown, the `fleet.Status.Replicas` will immediately be reduced by 1. However, the `desiredReplicas`, which should be `f.Status.AllocatedReplicas + int32(b.BufferSize.IntValue())`, doesn't update immediately. Then a scaling-out is triggered. And after a few seconds, the `f.Status.AllocatedReplicas` is updated then Agones find the GameServers are more than expected, so it will trigger a scaling-in.

**Comment by jie-bao** [comment] 2021-05-06 09:09
After some more investigation. I found the issue is because the GameServerSet reconciling happens before fleet auto-scaling. From debug logs, I can see:
```
- 15:01:03.404 Reconciling GameServerSet
- 15:01:03.404 Adding more gameservers
- 15:01:33.512 Event(v1.ObjectReference{Kind:"FleetAutoscaler", Namespace:"game-umi", Name:"autoscaler-test-scaledown", UID:"1be87e7f-75ab-4587-95f4-fa5d92de3561", APIVersion:"autoscaling.agones.dev/v1", ResourceVersion:"2605732210", FieldPath:""}): type: 'Normal' reason: 'AutoScalingFleet' Scaling fleet test-scaledown from 2 to 1
```

Note the `Reconciling GameServerSet` behavior is also a bit wired. It will compare the current `GSS.spec.replicas` vs `GSS.replicas` (equal to GSS.spec.replicas - the number of GS being deleted in our case, see https://github.com/googleforgames/agones/blob/main/pkg/gameserversets/controller.go#L357).  That means Whenever a GameServer is deleted, it will always trigger a new gameserver to be created, unless the fleetAutoScaler update the replica before the reconciling happens. So I think we need someway to ensure the sequence of those jobs.

**Comment by jie-bao** [comment] 2021-05-06 10:09
Besides the above solution, we may have another option: we can don't reduce the numbers of gameservers being deleted during reconciling. Then no extra gameservers will be created. But new gameservers can only be created after old gameservers deleted successfully.

**Comment by jie-bao** [comment] 2021-05-06 10:16
I want to add a `help wanted` tag, but it seems only the issue author can do it. @RayMeibergen can you help on this?

**Comment by markmandel** [comment] 2021-05-06 19:54
Coming around to this - and thanks for all the investigation and commentary.

Given that K8s as a whole is a self healing system, and generally doesn't work as a series of imperative commands -- I'm not sure that we (a) can solve this (b) actually _want_ to solve it.

The fact that the system overshoots on occasion in one direction or other -- as long as it's not in massive amounts, and eventually comes to the stable position in a somewhat timely manner, seems to be acceptable behaviour, and I would posit, it actually preferred given the overall benefits of a self healing system.

Rather than trying to solve this as a bug, I wonder if the issue [Configurable custom resync period for FleetAutoscaler](https://github.com/googleforgames/agones/issues/1955) should be explored more? Maybe with an GameServer event driven approach as well as a time based one like we have now?

@roberthbailey how do you feel about this?

**Comment by jie-bao** [comment] 2021-05-07 02:23
I think this may not be a bug but at least it's a defect. If we can make sure it won't cause massive amounts of gameservers scale in/out then it's acceptable.

I'm worried about the cases such as we shut down 50 gameservers the same time, then Agones will create 50 temporary gameservers. Usually it will trigger cluster scale up and add more nodes into K8S. This will raise cost and may also trigger alerts.

**Comment by markmandel** [comment] 2021-05-07 03:12
> I'm worried about the cases such as we shut down 50 gameservers the same time, then Agones will create 50 temporary gameservers. Usually it will trigger cluster scale up and add more nodes into K8S. This will raise cost and may also trigger alerts.

Have you seen anything like that happen in practice? I'm testing it locally with around 20 game servers, and I can't replicate it.

**Comment by jie-bao** [comment] 2021-05-07 05:51
I tried 20 game servers and can successfully reproduce it as follow:

I create a fleet with 5 buffer, then allocate 20 game servers. Then I get the game server list:
![image](https://user-images.githubusercontent.com/55120303/117403450-c4398500-af3a-11eb-9c6e-6e487556baa2.png)

Then I use a script to delete all the allocated game servers, it will automatically create 20 new game servers:
![image](https://user-images.githubusercontent.com/55120303/117403569-f3e88d00-af3a-11eb-8dd5-bc1f4ceaae64.png)

And after a few seconds, the temp gameservers are shutdown, only 5 remained:
![image](https://user-images.githubusercontent.com/55120303/117403704-301bed80-af3b-11eb-86d5-1a6bc513150b.png)

You can also notice 2 of the 5 ready gameservers in the final stage are not the same ones in the first picture.

**Comment by markmandel** [comment] 2021-05-07 15:00
Given that player throughput in a real world scenario is not going to drop that quickly, is this a real concern or issue?

Even in a maintenance window scenario, game sessions are going to jitter exit over time.

I guess it also becomes a question: What do we want to be optimising for? Having a new GameServer come up as fast as possible so you can get a player through (what we do currently), or extend the time to spin up a new GameServer to ensure resource usage optimisation?

If you are autoscaling your cluster, it's going to self downscale and adjust over time as well (10 minutes, I believe on GKE). At scale, this issue seems like a micro optimisation to me? Everything self heals pretty quickly.

**Comment by jie-bao** [comment] 2021-05-08 02:31
> Given that player throughput in a real world scenario is not going to drop that quickly, is this a real concern or issue?
>
> Even in a maintenance window scenario, game sessions are going to jitter exit over time.

I don't think in a real world this scenario won't happen. We are trying to run a session based game targets 100k peak CCU. Each game session can hold 50 players. Then we will have 2k gameservers concurrently. Each session last 30 minutes. Then there will be 2k/30 = 66.7 gameserver terminated per minute. If the fleet autoscaler resync every 30 seconds, we will have 33.3 additional gameservers per round. 
 
> I guess it also becomes a question: What do we want to be optimising for? Having a new GameServer come up as fast as possible so you can get a player through (what we do currently), or extend the time to spin up a new GameServer to ensure resource usage optimisation?

I think we might have both? Can we add new parameter like `SchedulingStrategy` to choose which way we want?

> If you are autoscaling your cluster, it's going to self downscale and adjust over time as well (10 minutes, I believe on GKE). At scale, this issue seems like a micro optimisation to me? Everything self heals pretty quickly.

For a 30 minutes session game and assume the gameservers being deleted continuously (no nodes will be scaled up/down because we always need nodes for hosting additional gameservers). The additional cost will be 1.66% (1/30 gameservers deleted per minute, 1/30/2 per autoscaler sync round). Shorter game sessions will have more additional costs, vice versa.

**Comment by markmandel** [comment] 2021-05-08 05:47
> Then there will be 2k/30 = 66.7 gameserver terminated per minute

So you'll average a surge of 1.1 game servers per second, matching the rate of shutdown and replacement. That doesn't seem like a lot on a game with 100k peak CCU.

**Comment by jie-bao** [comment] 2021-05-08 07:10
> > Then there will be 2k/30 = 66.7 gameserver terminated per minute
> 
> So you'll average a surge of 1.1 game servers per second, matching the rate of shutdown and replacement. That doesn't seem like a lot on a game with 100k peak CCU.

Yes, but fleetautoscaler will do synchronising every 30 seconds, so there will be 33.3 gameservers accumulated before synchronising.

**Comment by markmandel** [comment] 2021-05-08 14:47
> 
> Yes, but fleetautoscaler will do synchronising every 30 seconds, so there will be 33.3 gameservers accumulated before synchronising.

No there won't. The fleet autoscaler only adjusts the fleet size every thirty seconds if the buffer level is not met (either positively or negatively). If there are already a buffer of gameservers in place, the autoscaler will do nothing.

I think you are assuming the autoscaler deletes gameservers or something, but it doesn't.

**Comment by jie-bao** [comment] 2021-05-10 01:58
> > Yes, but fleetautoscaler will do synchronising every 30 seconds, so there will be 33.3 gameservers accumulated before synchronising.
> 
> No there won't. The fleet autoscaler only adjusts the fleet size every thirty seconds if the buffer level is not met (either positively or negatively). If there are already a buffer of gameservers in place, the autoscaler will do nothing.
> 
> I think you are assuming the autoscaler deletes gameservers or something, but it doesn't.

I know it doesn't. But autoscaler is responsible for adjusting the GameServerSet size. I think the issue here is before the adjusting,  the GameServerSet will keep the target replica number unchanged. So during one autoscale sync period, the additional gameservers will be accumulated.

**Comment by markmandel** [comment] 2021-05-11 17:40
> I think the issue here is that before the adjusting, the GameServerSet will keep the target replica number unchanged. So during one autoscale sync period, the additional gameservers will be accumulated.

This only happens on downscale, and rather than saying this is a bug - I would argue that this is "works as intended". The Autoscaler fires every 30 seconds - that was built that way by design.

I'll reiterate a previous comment:

> Rather than trying to solve this as a bug, I wonder if the issue [Configurable custom resync period for FleetAutoscaler](https://github.com/googleforgames/agones/issues/1955) should be explored more? Maybe with an GameServer event driven approach as well as a time based one like we have now?

I think this is a reasonable feature 👍🏻 and could be interesting to explore more as a feature.

**Comment by jie-bao** [comment] 2021-05-12 03:56
> I think this is a reasonable feature 👍🏻 and could be interesting to explore more as a feature.

I think above feature can mitigate the impact and worth doing. But it still can't solve the root problem. Those temp created gameserver will cause issues in some number-sensitive system such as billing.

Personally I'd like to implement a "lazy reconciling" feature. In this mode we can wait deleting gameservers fully removed before creating new gameservers during reconciling. WDYT?

**Comment by zmerlynn** [comment] 2022-11-14 23:08
Looks like a consensus was never reached - closing this for now. Please re-open if you wish to reengage!

**Closed by zmerlynn** 2022-11-14 23:08 UTC
Labels: kind/bug, wontfix
