### ISSUE TITLE
Pass game port to container as env variable

### ISSUE THREAD

**Issue by D3m1urg3** [googleforgames/agones#2201] opened 2021-07-28 10:28 UTC
**Is your feature request related to a problem? Please describe.**
I want the gameserver pod to be aware of its external udp port and have that information available through an environmental variable.

With the server running i can use the sdk (gameserver method) to get the information and send it via grpc to a registry service. But there are operations at OS level that cannot be achieve as the information is not available. 

For instance if I want to log stdout to a file in a persistent volume and use the server ip-port as name i cannot do it.

Kubernetes provides support to pass information about the pod to the containers ([Expose Pod Information to Containers Through Environment Variables](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
)). Using that feature I can obtain the gameserver ip to be used at OS level but i don't have access to the port that agones decided to expose externally.

**Describe the solution you'd like**
I will like to have a mechanism to access to the gameserver address and port information at os level without running sdk gameserver method.

**Describe alternatives you've considered**
I've been reading all the documentation I could find but there is no way to access the information I require as far as I know.

**Comment by markmandel** [comment] 2021-07-28 15:00
This looks like duplicate of #1524 - which we closed, because as soon as we open this gate, we can't close it - and a GameServer config doesn't map well to env variables.

Can you expand more about your use case? I'm pretty sure we can work out a way to script what you need through the SDK.

**Comment by D3m1urg3** [comment] 2021-07-29 06:27
Indeed what is ask in #1524 is what I need. Because of the nature of our backend we need to have the ip and game port data before executing the gameserver. The ip and port is indeed a parameter required by the gameserver itself for id, logging, and others.

Is there any way to access this information from within the container without launching the gameserver other than env variables?

**Comment by markmandel** [comment] 2021-07-29 18:16
> Is there any way to access this information from within the container without launching the gameserver other than env variables?

Write a small (bash even? curl + jq could probably do the trick in a pinch) program that starts up, hits the SDK for the required info, and then starts up your game process with the information it has gathered from the SDK.

**Comment by D3m1urg3** [comment] 2021-07-30 06:03
Thanks Mark.

I solved the issue pretty much the same way you propose. I've made a little  c++ exec which does what you propose. It hits the sdk and generates a bash script in order to set the env variables.

 I will try go for the bash + jq solution as  I feel mine is a little bit overkill.

Cheers.

**Comment by D3m1urg3** [comment] 2021-07-30 08:14
Implemented the bash script using curl + jq without any problem

**Closed** 2021-07-30 08:14 UTC
Labels: kind/feature
