### ISSUE TITLE
Fleet Image Edit causes an infinite create/destroy loop

### ISSUE THREAD

**Issue by TimoSchmechel** [googleforgames/agones#975] opened 2019-08-01 07:09 UTC
**What happened**:
I created a fleet using `kubectl apply -f fleet.yaml` then edited the file to change the container image being used, afterwards it got stuck in a loop of continuously creating the new gameservers and then destroying them again. 

NOTE: This doesnt seem to happen when using `kubectl edit fleet test-fleet`

**What you expected to happen**:
I was trying to update the image used by the fleet to update the running game servers to a new build. 

**How to reproduce it (as minimally and precisely as possible)**:
Use the yaml file below and run `kubectl apply -f fleet.yaml` then wait till the server is ready, now edit the file to change the image version from 11 to 10 (or any other valid version). Run `kubectl apply -f fleet.yaml` again. Use `kubectl get gs` to watch the pods get created/destroyed forever

```
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
  name: test-fleet
spec:
  replicas: 1
  template:
    spec:
      ports:
      - name: default
        containerPort: 1234
        protocol: UDP
      template:
        spec:
          containers:
          - name: test
            image: gcr.io/agones-images/udp-server:0.11
            resources:
              limits:
                memory: "50Mi"
                cpu: "0.2"
```

**Environment**:
- Agones version: 
agones-0.11.0
- Kubernetes version (use `kubectl version`):
Client Version: v1.14.3
Server Version: v1.11.10-gke.5
- Cloud provider or hardware configuration:
GKE
- Install method (yaml/helm):
yaml
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment] 2019-08-12 14:34
Hello @TimoSchmechel ,
Thanks for reporting this issue.
I was not able to reproduce it on recent 0.12 version of Agones.
When I update `fleet.yaml` from version 0.14 to 0.13 and perform:
```
kubectl apply -f ../examples/simple-udp/fleet.yaml
```
Old GameServers moved to a Shutdown stage and new Gameservers got created:
```
 kubectl describe gs simple-udp-dr82k-2tvlj
...
  Template:
    Metadata:
      Creation Timestamp:  <nil>
    Spec:
      Containers:
        Image:  gcr.io/agones-images/udp-server:0.13
        Name:   simple-udp
        Resources:
          Limits:
            Cpu:     20m
            Memory:  64Mi
          Requests:
            Cpu:     20m
            Memory:  64Mi
Status:
  Address:    34.83.19.42
  Node Name:  gke-test-cluster23-default-7ed05713-w506
  Ports:
    Name:          default
    Port:          7031
  Reserved Until:  <nil>
  State:           Ready
Events:
  Type    Reason          Age   From                   Message
  ----    ------          ----  ----                   -------
  Normal  PortAllocation  44s   gameserver-controller  Port allocated
  Normal  Creating        44s   gameserver-controller  Pod simple-udp-dr82k-2tvlj created
  Normal  Scheduled       44s   gameserver-controller  Address and port populated
  Normal  Ready           42s   gameserver-controller  SDK.Ready() complete
  Normal  RequestReady    42s   gameserver-sidecar     SDK state change
```

**Comment by aLekSer** [comment] 2019-08-12 14:35
One issue which is similar to this one is running `kubectl edit gs GSName` and updating container image to another version. Leads to change in config, but GameServers does not recreated.

**Comment by TimoSchmechel** [comment] 2019-08-13 02:18
@aLekSer I have just updated my Agones Cluster to version 0.12 and couldnt reproduce it anymore either. Seems like this was fixed in this version.

I think the issue with editing a GameServer is different though. At least to my knowledge I thought that editing a GameServer shouldnt have any effect as `edit` should be done on the fleet level. I could be wrong though.

**Comment by aLekSer** [comment] 2019-08-13 12:59
Yes, GS edit is not documented so there should be no expectations on the results.
If there is not issues with Fleets, I think you can close this issue.

**Closed** 2019-08-14 00:22 UTC
Labels: kind/bug

**Comment by roberthbailey** [comment] 2019-09-24 07:17
> One issue which is similar to this one is running kubectl edit gs GSName and updating container image to another version leads to change in GameServer config, but GameServers was not recreated.

I just ran across this right now. I think we should either fix it (so that editing a game server updates the associated pod spec) or document that it is not supported and work towards adding a webhook to reject edits. Right now the user experience is terrible -- the game server says I'm running container A and the pod says I'm running container B. Similarly, if I manually delete the pod associated with the game server, it seems to stay deleted and not get recreated.

**Comment by aLekSer** [comment] 2019-09-24 09:16
@roberthbailey Should we open a separate issue/-s to track that or reopen this one?
