### ISSUE TITLE
sdks/cpp needs unit tests

### ISSUE THREAD

**Issue by devjgm** [googleforgames/agones#719] opened 2019-04-17 16:28 UTC
The C++ SDK needs some unit tests to show that it works, and to allow people to refactor the code with (some) confidence it won't be broken. The standard unit testing framework that I'd suggest is https://github.com/google/googletest

**Comment by dsazonoff** [comment] 2019-04-17 20:38
I'm working on it now in scope of #134.

**Comment by roberthbailey** [comment] 2019-07-17 08:23
This is a dupe of https://github.com/googleforgames/agones/issues/905 and since that one has more details, I'm going to close this one and use it as the canonical issue.

**Closed by roberthbailey** 2019-07-17 08:23 UTC
Labels: area/build-tools, area/tests
