### ISSUE TITLE
Tests fail with `NuGet.targets(128,5): error : '1.28.0-0764169' is not a valid version string.`

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2801] opened 2022-11-10 16:57 UTC
The `tests` phase of AgonesBot is failing with:

```
+ cd ./sdks/csharp/test
+ dotnet test -c Release

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.425

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
/usr/share/dotnet/sdk/3.1.425/NuGet.targets(128,5): error : '1.28.0-0764169' is not a valid version string. (Parameter 'value') [/go/src/agones.dev/agones/sdks/csharp/test/csharp-sdk-test.csproj]
make[1]: *** [includes/sdk.mk:88: run-sdk-command] Error 1
```

Examples:
* https://github.com/googleforgames/agones/pull/2789#issuecomment-1310577029
* https://github.com/googleforgames/agones/pull/2789#issuecomment-1310592796

**Comment by zmerlynn** [comment] 2022-11-10 17:09
I wasn't initially able to reproduce this locally, but I notice that @agones-bot is using `SDK Version: 3.1.425` and my local docker build container is using `SDK Version: 3.1.424`.

**Comment by markmandel** [comment] 2022-11-10 17:39
This is a duplicate of https://github.com/googleforgames/agones/issues/2018

**Closed** 2022-11-10 17:41 UTC
Labels: kind/bug
