### ISSUE TITLE
Implementing tracing capability to the allocator

### ISSUE THREAD

**Issue by valentintorikian** [googleforgames/agones#2597] opened 2022-05-26 18:13 UTC
**Is your feature request related to a problem? Please describe.**
The allocation flow being in the hot path to actually get players in game I think it would be a good idea to have some tracing capability in it so that it can plug into the upstream matchmaking system (or other ways of allocating). This would give a more complete picture of the allocation process timings and performances.

**Describe the solution you'd like**
Implement opentracing/opencensus (or compatible equivalent) into the allocator flow.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Thiryn** [comment] 2022-05-30 08:38
I actually needed that feature to debug a race condition not too long ago, I ended up shoehorning a simple opentelemetry implementation in the controllers. I'm wondering what kind of production readiness level would be required for this, i.e. would we need e2e tests to ensure expected traces are produced?

**Comment by markmandel** [comment] 2022-07-28 16:35
Doing triage, marking this as duplicate of #1012 - but definitely would love help in this area.

**Closed by markmandel** 2022-07-28 16:35 UTC
Labels: kind/feature, duplicate
