### ISSUE TITLE
Allow the agones-controller to work with multiple pods

### ISSUE THREAD

**Issue by nanasi880** [googleforgames/agones#1950] opened 2021-01-15 11:13 UTC
**Is your feature request related to a problem? Please describe.**
When the node on which agones-controller is running crashes, Agones goes offline temporarily.
To avoid this, is it possible to make agones-controller work on multiple pods/nodes?

**Describe the solution you'd like**
For availability, we want to run multiple agones-controller pods.

**Describe alternatives you've considered**
None.

**Additional context**
https://app.slack.com/client/T9CTF3PCG/C9DGM5DS8/thread/C9DGM5DS8-1610696003.004900

**Comment by danieloliveira079** [comment] 2021-01-15 11:32
For the sake of context, there is an example of how to run leader election using client-go packages https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go

**Comment by markmandel** [comment] 2021-01-15 16:29
This is duplicate of #1296, so I'm going to close this issue and we can move conversation over there 👍🏻

**Closed** 2021-01-15 16:30 UTC
Labels: duplicate, kind/feature
