### ISSUE TITLE
Release for AArch64/ARM64

### ISSUE THREAD

**Issue by stevefan1999-personal** [googleforgames/agones#2223] opened 2021-08-15 04:46 UTC
**Is your feature request related to a problem? Please describe.**
I would like to run some Agones on Ampere/Graviton2

**Describe the solution you'd like**
Add aarch64/arm64 to the build matrix

**Describe alternatives you've considered**
Run the game server myself using deployment

**Comment by markmandel** [comment] 2021-08-16 18:52
Is this a duplicate of #2216 ?

**Comment by stevefan1999-personal** [comment] 2021-08-17 02:11
@markmandel kind of, but I want to see controller components to be compatible with ARM64 as well, that's much easier than porting the SDK atm

**Comment by roberthbailey** [comment] 2021-08-19 04:24
FYI, right now the only container that we build for multiple architectures is the sdk sidecar (linux and windows).

**Comment by markmandel** [comment] 2021-08-19 16:31
Let's combine this with #2216 since it's the same work, the only difference is one is "all components" and the other is "just the SDK". I think there is more data in #2216 so I suggest closing this one and porting some of the expanded use case over to there, just so we have one place to track this work. 

Any objections?

**Comment by markmandel** [comment] 2021-08-24 22:37
Consolidated with #2216. Closing as duplicate.

**Closed by markmandel** 2021-08-24 22:37 UTC
Labels: kind/feature, duplicate
