### ISSUE TITLE
hostNetwork for GameServer

### ISSUE THREAD

**Issue by bburghaus** [googleforgames/agones#1389] opened 2020-03-04 20:37 UTC
Currently we run GameServers on host network. The sidecar only runs on a static grpc/http port, creating port conflicts. 

Adding a hostNetwork boolean flag to the GameServer spec will ask the controller to dynamically create the grpc/http ports needed for the sidecar.

Alternatively, we considered making the list of ports applicable to any container in the pod, as described in [#151](https://github.com/googleforgames/agones/issues/151#issuecomment-385838436), and add a new portPolicy for adding dynamic ports for the sidecar.

Example GameServer yaml with `hostNetwork`:
```
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: gameserver
  namespace: default
spec:
  ports:
  - name: default
    portPolicy: Passthrough
  template:
    spec:
      hostNetwork: true
      containers:
      - name: gameserver
      ...
```

**Comment by markmandel** [comment] 2020-03-04 20:48
To give you a quick response: I don't think we'll ever support hostnetwork. In fact we should probably disallow it with validation -- for exactly the reason you ran into -- sidecars will fail.

So, this is basically "works as intended".

What is your reason for running on hostnetwork? Maybe we can find an alternate path for you?

**Comment by bburghaus** [comment] 2020-03-04 20:59
Our main reasons were 1) performance concerns and 2) historical. 

It seems through an outside conversation that there is little to no performance gain from running on host network, so we might just have to make the change to stop running on it.

**Comment by markmandel** [comment] 2020-03-04 21:45
Got it - totally reasonable. I know I [originally did the same thing](https://www.compoundtheory.com/scaling-dedicated-game-servers-with-kubernetes-part-1-containerising-and-deploying/) because in many ways it is simpler. Also, because I wasn't aware of hostPost :smile: 

But the benefits of network segregation between game servers and the ability to use sidecars was too powerful to pass up, and routing data through iptables (which is what hostPort does) is very, very fast - and generally imperceptible.

So - marking as "wontfix" and closing - but thanks for bringing it up.

As a side note - I've got an doc I wrote internally I've been meaning to put on the site as a FAQ, which covers this question too, since it's a regularly one - so thanks for the extra incentive for making that happen.

**Closed by markmandel** 2020-03-04 21:45 UTC
Labels: kind/feature, wontfix

**Comment by jasondamour** [comment] 2021-11-21 17:49
@markmandel, I think I have a valid use case which could require hostNetwork. Our application requires a vast number of UDP ports (>10,000 UDP ports). We are running today on Kubernetes by implementing the following:
- hostNetwork on pods
- taints/tolerations + nodeSelectors + anti-affinity to schedule a single pod per node, no other pods allowed on those nodes

So as long as our application doesn't listen on the same ports as the sidecars, then it would work. So my ask is please don't enforce validation on the pod spec :D
