### ISSUE TITLE
NodeExternalDNS does not work

### ISSUE THREAD

**Issue by ctanaka-aim** [googleforgames/agones#2464] opened 2022-02-02 03:05 UTC
**What happened**:
NodeExternalDNS does not work.

**What you expected to happen**:
The domain should be returned.

**How to reproduce it (as minimally and precisely as possible)**:
When installing agones with helm, I set agones.featureGates=NodeExternalDNS=true, but the result is the same as normal install.

Note that in values.yaml, there is a line   
```
featureGates=NodeExternalDNS=true
disableMTLS: true
disableTLS: true
```
in values.yaml.

The installation command is as follows
```
helm repo add agones https://agones.dev/chart/stable
helm repo update
helm install my-release --namespace agones-system -f values.yaml agones/agones
```

If you create gameservers in this state and do `kubectl get gs`, you will get the following state.
```
$ kubectl get gs
NAME                       STATE   ADDRESS        PORT   NODE                                                 AGE
simple-game-server-mfkkb   Ready   xxx.xxx.xxx.127   7091   gke-test-ctanaka-agones-default-pool-xxxxxxxxxx  3s
```

And if you do an allocate with curl, the result will look like this
````
$ curl -H "Content-Type: application/json" --data '{"namespace":"default"}' http://xxx.xxx.xxx.171/gameserverallocation -X POST
{"gameServerName":"simple-game-server-mfkkb","ports":[{"name":"default","port":7091}],"address":"xxx.xxx.xxx.127","nodeName":"gke-test-ctanaka-agones-default-pool-xxxxxxxxxx"}
````

**Environment**:
- Agones version: 1.19.0 or 1.20.0
- Kubernetes version (use `kubectl version`): v1.21.5-gke.1802
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm

**Comment by roberthbailey** [comment] 2022-02-02 05:13
When picking the address to return, we pick in order: ExternalDNS, ExternalIP, InternalDNS, InternalIP ([source](https://github.com/googleforgames/agones/blob/main/pkg/gameservers/gameservers.go#L44-L78)). 

Since you are running on GKE this is working as intended, as GKE doesn't set an address on nodes with an external DNS name.

To confirm, I created a cluster and inspected a node:

```
...
  addresses:
  - address: 10.128.15.209
    type: InternalIP
  - address: 34.68.12.140
    type: ExternalIP
  - address: gke-issue-2464-default-pool-7e111704-rm4j.us-central1-f.c.robertbailey-agones.internal
    type: InternalDNS
  - address: gke-issue-2464-default-pool-7e111704-rm4j.us-central1-f.c.robertbailey-agones.internal
    type: Hostname
...
```

As you can see the node has an external IP (which is what is returned during allocation) but no external DNS.

**Comment by ctanaka-aim** [comment] 2022-02-03 06:27
I understand now, thank you.
I'm sorry to ask more questions.
Is this the correct procedure for setting up externalDNS?
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md

**Comment by roberthbailey** [comment] 2022-02-05 04:42
I haven't seen that link before but it looks to me like that creates DNS records for Kubernetes services and Ingress resources, not for all nodes in a cluster.

**Comment by ctanaka-aim** [comment] 2022-02-07 09:49
Thank you for your answer.
Yes, I tried that, but it seems to be different.
I'd like to know if you have any reference material on external dns settings.

**Comment by markmandel** [comment] 2022-02-08 20:10
Unfortunately GKE doesn't have a way to provide a DNS for each node as part of the product.

That beings said, you can get a DNS entry for any GCE instance (which a GKE node is), like so:
https://twitter.com/Neurotic/status/1489650458109042689

(reverse the IP and append to `bc.googleusercontent.com`) - if you `nslookup` any GCP IP, you can see the FQDN available.

**Comment by ctanaka-aim** [comment] 2022-02-09 06:29
> Unfortunately GKE doesn't have a way to provide a DNS for each node as part of the product

I understand.

Thank you very much! 
I will try to do it the way you suggested.

**Comment by markmandel** [comment] 2022-02-16 23:25
We happy to close this ticket now? Wanted to check before closing.

**Comment by jordo** [comment] 2022-02-18 15:07
@ctanaka-aim to have external-dns autocreate dns node-name entries in your zone, you can add this to the external-dns helm chart: (note the addition of `- node`)
```
fqdnTemplates:
 - "{{.Name}}.YOURDOMAIN.COM"
sources:
  - service
  - ingress
  - node
```

**Comment by ctanaka-aim** [comment] 2022-02-24 08:30
Sorry for the delay in confirmation.

Thank you!
I'll try that method.

> We happy to close this ticket now? 

I'd like you to wait a little longer.

**Comment by markmandel** [comment] 2022-02-24 18:17
Looking at https://github.com/bitnami/charts/tree/master/bitnami/external-dns (which I assume it what you are referring to) - this only coordinates records for Services? I don't see any mention in the docs about nodes?

It could be I'm missing seeing some documentation though?

**Comment by jordo** [comment] 2022-02-24 19:43
@markmandel  see the sources configuration here:

https://artifacthub.io/packages/helm/external-dns/external-dns?modal=values

The default for external-dns source objects to monitor are 'ingress', and 'service', but can be expanded to others.   Example, you can add 'node' here if you want.

**Comment by markmandel** [comment] 2022-02-24 19:46
Oh fancy! Good to know!

**Comment by jordo** [comment] 2022-02-24 19:47
iirc, I had to inspect the external-dns source to figure out what object types it supports...  (It does support CRD which is nice).  We are currently using it to resolve nodes that host agones gameservers

**Comment by markmandel** [comment] 2022-03-15 19:37
Since this isn't an actual Agones issue - should we close this ticket now?

Unless you wanted to create some documentation on the site to provide a common solution?

**Comment by roberthbailey** [comment] 2022-03-30 02:45
Thanks for following up!

**Closed by roberthbailey** 2022-03-30 02:45 UTC
Labels: question
